# Generated by Django 3.1.5 on 2021-01-08 20:52
import tinymce
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210106_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='place_short_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='place_long_description',
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=13, max_digits=17, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=13, max_digits=17, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
