# Generated by Django 3.1.5 on 2021-01-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210112_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_long_description',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_short_description',
            new_name='short_description',
        ),
    ]
